function cav24PerimData = importPerimFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CAV24PERIMDATA = IMPORTPERIMFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  CAV24PERIMDATA = IMPORTPERIMFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  cav24PerimData = importPerimFile("/projectnb/turbomac/REBECCA/cavSym2024/areaPerimData/cav24PerimData.csv", [2, 502]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Jul-2024 14:53:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, 502];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "U267nB", "U267B2", "U267B3", "U267B4", "U100nB", "U100B2", "U100B3", "U100B4", "U267BA2", "U267BA3", "U267BA4", "U100BA2", "U100BA3", "U100BA4", "Var16", "Var17", "Var18"];
opts.SelectedVariableNames = ["Time", "U267nB", "U267B2", "U267B3", "U267B4", "U100nB", "U100B2", "U100B3", "U100B4", "U267BA2", "U267BA3", "U267BA4", "U100BA2", "U100BA3", "U100BA4"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var16", "Var17", "Var18"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var16", "Var17", "Var18"], "EmptyFieldRule", "auto");

% Import the data
cav24PerimData = readtable(filename, opts);

%% Convert to output type
cav24PerimData = table2array(cav24PerimData);
end


X
for i = 1:121
