function b = bFn(Nx,Ny,dx,dy,u,v,rho,dt)
    %% forcing function for step 11
    b = zeros(Nx,Ny);
    for i = 2:Nx-1
        for j = 2:Ny-1
            b(i,j) = -rho *( ((u(i+1,j) - u(i-1,j)) / (2*dx)) ^2 + ...
                2*((u(i,j+1) - u(i,j-1)) / (2*dy)) *...
                (v(i+1,j) - v(i-1,j)) / (2*dx)...
                + ((v(i,j+1) - v(i,j-1)) / (2*dy)) ^2 ) + ...
                rho/dt * ((u(i+1,j) - u(i-1,j)) / (2*dx) +...
                (v(i,j+1) - v(i,j-1)) / (2*dy));
        end
    end

%     i = 1;
%     for j = 2:Ny-1
%         b(i,j) = -rho *( ((u(i+1,j) - u(end-1,j)) / (2*dx)) ^2 + ...
%                 2*((u(i,j+1) - u(i,j-1)) / (2*dy)) *...
%                 (v(i+1,j) - v(end-1,j)) / (2*dx)...
%                 + ((v(i,j+1) - v(i,j-1)) / (2*dy)) ^2 ) + ...
%                 rho/dt * ((u(i+1,j) - u(end-1,j)) / (2*dx) +...
%                 (v(i,j+1) - v(i,j-1)) / (2*dy));
%         b(end,j) = b(i,j);
%     end
% 
%     % Neumann BC at top and bottom
%         b(:,1) = b(:,2);    
%         b(:,end) = b(:,end-1); 
    
end